version: "3.1"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    expose:
      - '5432'
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - '6379'
    