version: "3.1"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    # volumes:
    #   - ./db_scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db